--------------------------------------------------------
--  File created - Thursday-September-13-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SQ_ALIMENTACAO
--------------------------------------------------------

   CREATE SEQUENCE  "HT"."SQ_ALIMENTACAO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ATIVIDADE_FISICA
--------------------------------------------------------

   CREATE SEQUENCE  "HT"."SQ_ATIVIDADE_FISICA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_PESO
--------------------------------------------------------

   CREATE SEQUENCE  "HT"."SQ_PESO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 221 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_PRESSAO
--------------------------------------------------------

   CREATE SEQUENCE  "HT"."SQ_PRESSAO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_USER
--------------------------------------------------------

   CREATE SEQUENCE  "HT"."SQ_USER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table T_ALIMENTACAO
--------------------------------------------------------

  CREATE TABLE "HT"."T_ALIMENTACAO" 
   (	"ID_ALIMENTACAO" NUMBER, 
	"DS_ALIMENTAO" VARCHAR2(255 BYTE), 
	"N_CALORIAS" NUMBER, 
	"DT_ALIMENTACAO" DATE, 
	"T_TIPO_ALIM_ID_TIPO_ALIM" NUMBER, 
	"T_USUARIO_ID_USUARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_ATIVIDADE
--------------------------------------------------------

  CREATE TABLE "HT"."T_ATIVIDADE" 
   (	"ID_ATIVIDADE" NUMBER, 
	"DS_ATIVIDADE" VARCHAR2(255 BYTE), 
	"N_CALORIAS_GASTAS" NUMBER, 
	"DT_ATIVIDADE" DATE, 
	"T_TIPO_ATIV_ID_TIPO_ATIV" NUMBER, 
	"T_USUARIO_ID_USUARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_PESOS
--------------------------------------------------------

  CREATE TABLE "HT"."T_PESOS" 
   (	"ID_PESAGEM" NUMBER, 
	"N_PESO" NUMBER, 
	"DT_PESAGEM" DATE, 
	"T_USUARIO_ID_USUARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_PRESSAO
--------------------------------------------------------

  CREATE TABLE "HT"."T_PRESSAO" 
   (	"ID_PRESSAO" NUMBER, 
	"N_PRESSAO_SIST" NUMBER, 
	"N_PRESSAO_DIAS" NUMBER, 
	"DT_PRESSAO" DATE, 
	"T_USUARIO_ID_USUARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_TIPO_ALIM
--------------------------------------------------------

  CREATE TABLE "HT"."T_TIPO_ALIM" 
   (	"ID_TIPO_ALIM" NUMBER, 
	"DS_TIPO_ALIMENTO" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_TIPO_ATIV
--------------------------------------------------------

  CREATE TABLE "HT"."T_TIPO_ATIV" 
   (	"ID_TIPO_ATIV" NUMBER, 
	"DS_TIPO_ATIVIDADE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_USUARIO
--------------------------------------------------------

  CREATE TABLE "HT"."T_USUARIO" 
   (	"ID_USUARIO" NUMBER, 
	"NM_USUARIO" VARCHAR2(255 CHAR), 
	"DT_NASC" DATE, 
	"CD_GENERO" CHAR(1 BYTE), 
	"VL_ALTURA" NUMBER, 
	"DS_EMAIL" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HT.T_ALIMENTACAO
SET DEFINE OFF;
REM INSERTING into HT.T_ATIVIDADE
SET DEFINE OFF;
Insert into HT.T_ATIVIDADE (ID_ATIVIDADE,DS_ATIVIDADE,N_CALORIAS_GASTAS,DT_ATIVIDADE,T_TIPO_ATIV_ID_TIPO_ATIV,T_USUARIO_ID_USUARIO) values (10,'Teste',100,to_date('13-SEP-18','DD-MON-RR'),1,1);
Insert into HT.T_ATIVIDADE (ID_ATIVIDADE,DS_ATIVIDADE,N_CALORIAS_GASTAS,DT_ATIVIDADE,T_TIPO_ATIV_ID_TIPO_ATIV,T_USUARIO_ID_USUARIO) values (11,'Teste',100,to_date('13-SEP-18','DD-MON-RR'),2,1);
REM INSERTING into HT.T_PESOS
SET DEFINE OFF;
Insert into HT.T_PESOS (ID_PESAGEM,N_PESO,DT_PESAGEM,T_USUARIO_ID_USUARIO) values (197,46.5,to_date('13-SEP-18','DD-MON-RR'),1);
Insert into HT.T_PESOS (ID_PESAGEM,N_PESO,DT_PESAGEM,T_USUARIO_ID_USUARIO) values (198,49.4,to_date('13-SEP-18','DD-MON-RR'),1);
Insert into HT.T_PESOS (ID_PESAGEM,N_PESO,DT_PESAGEM,T_USUARIO_ID_USUARIO) values (199,52,to_date('13-SEP-18','DD-MON-RR'),1);
Insert into HT.T_PESOS (ID_PESAGEM,N_PESO,DT_PESAGEM,T_USUARIO_ID_USUARIO) values (200,55,to_date('13-SEP-18','DD-MON-RR'),1);
Insert into HT.T_PESOS (ID_PESAGEM,N_PESO,DT_PESAGEM,T_USUARIO_ID_USUARIO) values (201,69,to_date('13-SEP-18','DD-MON-RR'),1);
Insert into HT.T_PESOS (ID_PESAGEM,N_PESO,DT_PESAGEM,T_USUARIO_ID_USUARIO) values (202,75.5,to_date('13-SEP-18','DD-MON-RR'),1);
Insert into HT.T_PESOS (ID_PESAGEM,N_PESO,DT_PESAGEM,T_USUARIO_ID_USUARIO) values (203,83,to_date('13-SEP-18','DD-MON-RR'),1);
Insert into HT.T_PESOS (ID_PESAGEM,N_PESO,DT_PESAGEM,T_USUARIO_ID_USUARIO) values (204,89.5,to_date('13-SEP-18','DD-MON-RR'),1);
Insert into HT.T_PESOS (ID_PESAGEM,N_PESO,DT_PESAGEM,T_USUARIO_ID_USUARIO) values (195,40,to_date('13-SEP-18','DD-MON-RR'),1);
REM INSERTING into HT.T_PRESSAO
SET DEFINE OFF;
REM INSERTING into HT.T_TIPO_ALIM
SET DEFINE OFF;
Insert into HT.T_TIPO_ALIM (ID_TIPO_ALIM,DS_TIPO_ALIMENTO) values (1,'ALMOCO');
Insert into HT.T_TIPO_ALIM (ID_TIPO_ALIM,DS_TIPO_ALIMENTO) values (2,'CAFE DA MANHA');
Insert into HT.T_TIPO_ALIM (ID_TIPO_ALIM,DS_TIPO_ALIMENTO) values (3,'FRUTA');
Insert into HT.T_TIPO_ALIM (ID_TIPO_ALIM,DS_TIPO_ALIMENTO) values (4,'JANTAR');
Insert into HT.T_TIPO_ALIM (ID_TIPO_ALIM,DS_TIPO_ALIMENTO) values (5,'LANCHE LEVE');
REM INSERTING into HT.T_TIPO_ATIV
SET DEFINE OFF;
Insert into HT.T_TIPO_ATIV (ID_TIPO_ATIV,DS_TIPO_ATIVIDADE) values (1,'CAMINHADA');
Insert into HT.T_TIPO_ATIV (ID_TIPO_ATIV,DS_TIPO_ATIVIDADE) values (2,'CORRIDA');
Insert into HT.T_TIPO_ATIV (ID_TIPO_ATIV,DS_TIPO_ATIVIDADE) values (3,'MUSCULACAO');
Insert into HT.T_TIPO_ATIV (ID_TIPO_ATIV,DS_TIPO_ATIVIDADE) values (4,'PEDALADA');
REM INSERTING into HT.T_USUARIO
SET DEFINE OFF;
Insert into HT.T_USUARIO (ID_USUARIO,NM_USUARIO,DT_NASC,CD_GENERO,VL_ALTURA,DS_EMAIL) values (1,'Sidharta Rezende',to_date('17-JAN-79','DD-MON-RR'),'1',1.78,'sidharta.rezende@gmail.com');
--------------------------------------------------------
--  DDL for Index T_PESOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HT"."T_PESOS_PK" ON "HT"."T_PESOS" ("ID_PESAGEM", "T_USUARIO_ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HT"."T_USUARIO_PK" ON "HT"."T_USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_TIPO_ALIM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HT"."T_TIPO_ALIM_PK" ON "HT"."T_TIPO_ALIM" ("ID_TIPO_ALIM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_PRESSAO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HT"."T_PRESSAO_PK" ON "HT"."T_PRESSAO" ("ID_PRESSAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_ALIMENTACAO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HT"."T_ALIMENTACAO_PK" ON "HT"."T_ALIMENTACAO" ("ID_ALIMENTACAO", "T_TIPO_ALIM_ID_TIPO_ALIM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_TIPO_ATIV_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HT"."T_TIPO_ATIV_PK" ON "HT"."T_TIPO_ATIV" ("ID_TIPO_ATIV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table T_TIPO_ALIM
--------------------------------------------------------

  ALTER TABLE "HT"."T_TIPO_ALIM" ADD CONSTRAINT "T_TIPO_ALIM_PK" PRIMARY KEY ("ID_TIPO_ALIM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HT"."T_TIPO_ALIM" MODIFY ("DS_TIPO_ALIMENTO" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_TIPO_ALIM" MODIFY ("ID_TIPO_ALIM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_PESOS
--------------------------------------------------------

  ALTER TABLE "HT"."T_PESOS" ADD CONSTRAINT "T_PESOS_PK" PRIMARY KEY ("ID_PESAGEM", "T_USUARIO_ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HT"."T_PESOS" MODIFY ("T_USUARIO_ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_PESOS" MODIFY ("DT_PESAGEM" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_PESOS" MODIFY ("N_PESO" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_PESOS" MODIFY ("ID_PESAGEM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_PRESSAO
--------------------------------------------------------

  ALTER TABLE "HT"."T_PRESSAO" ADD CONSTRAINT "T_PRESSAO_PK" PRIMARY KEY ("ID_PRESSAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HT"."T_PRESSAO" MODIFY ("T_USUARIO_ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_PRESSAO" MODIFY ("N_PRESSAO_DIAS" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_PRESSAO" MODIFY ("N_PRESSAO_SIST" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_PRESSAO" MODIFY ("ID_PRESSAO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_TIPO_ATIV
--------------------------------------------------------

  ALTER TABLE "HT"."T_TIPO_ATIV" ADD CONSTRAINT "T_TIPO_ATIV_PK" PRIMARY KEY ("ID_TIPO_ATIV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HT"."T_TIPO_ATIV" MODIFY ("DS_TIPO_ATIVIDADE" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_TIPO_ATIV" MODIFY ("ID_TIPO_ATIV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_ALIMENTACAO
--------------------------------------------------------

  ALTER TABLE "HT"."T_ALIMENTACAO" ADD CONSTRAINT "T_ALIMENTACAO_PK" PRIMARY KEY ("ID_ALIMENTACAO", "T_TIPO_ALIM_ID_TIPO_ALIM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HT"."T_ALIMENTACAO" MODIFY ("T_USUARIO_ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_ALIMENTACAO" MODIFY ("T_TIPO_ALIM_ID_TIPO_ALIM" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_ALIMENTACAO" MODIFY ("DT_ALIMENTACAO" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_ALIMENTACAO" MODIFY ("N_CALORIAS" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_ALIMENTACAO" MODIFY ("ID_ALIMENTACAO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_USUARIO
--------------------------------------------------------

  ALTER TABLE "HT"."T_USUARIO" ADD CONSTRAINT "T_USUARIO_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HT"."T_USUARIO" MODIFY ("DS_EMAIL" CONSTRAINT "NNC_T_USUARIO_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_USUARIO" MODIFY ("VL_ALTURA" CONSTRAINT "NNC_T_USUARIO_ALTURA" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_USUARIO" MODIFY ("CD_GENERO" CONSTRAINT "NNC_T_USUARIO_GENERO" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_USUARIO" MODIFY ("DT_NASC" CONSTRAINT "NNC_T_USUARIO_DT_NASC" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_USUARIO" MODIFY ("NM_USUARIO" CONSTRAINT "NNC_T_USUARIO_NM_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_USUARIO" MODIFY ("ID_USUARIO" CONSTRAINT "NNC_T_USUARIO_ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_ATIVIDADE
--------------------------------------------------------

  ALTER TABLE "HT"."T_ATIVIDADE" MODIFY ("T_USUARIO_ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_ATIVIDADE" MODIFY ("T_TIPO_ATIV_ID_TIPO_ATIV" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_ATIVIDADE" MODIFY ("DT_ATIVIDADE" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_ATIVIDADE" MODIFY ("N_CALORIAS_GASTAS" NOT NULL ENABLE);
  ALTER TABLE "HT"."T_ATIVIDADE" MODIFY ("ID_ATIVIDADE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table T_ALIMENTACAO
--------------------------------------------------------

  ALTER TABLE "HT"."T_ALIMENTACAO" ADD CONSTRAINT "T_ALIMENTACAO_T_TIPO_ALIM_FK" FOREIGN KEY ("T_TIPO_ALIM_ID_TIPO_ALIM")
	  REFERENCES "HT"."T_TIPO_ALIM" ("ID_TIPO_ALIM") ENABLE;
  ALTER TABLE "HT"."T_ALIMENTACAO" ADD CONSTRAINT "T_ALIMENTACAO_T_USUARIO_FK" FOREIGN KEY ("T_USUARIO_ID_USUARIO")
	  REFERENCES "HT"."T_USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_ATIVIDADE
--------------------------------------------------------

  ALTER TABLE "HT"."T_ATIVIDADE" ADD CONSTRAINT "T_ATIVIDADE_T_TIPO_ATIV_FK" FOREIGN KEY ("T_TIPO_ATIV_ID_TIPO_ATIV")
	  REFERENCES "HT"."T_TIPO_ATIV" ("ID_TIPO_ATIV") ENABLE;
  ALTER TABLE "HT"."T_ATIVIDADE" ADD CONSTRAINT "T_ATIVIDADE_T_USUARIO_FK" FOREIGN KEY ("T_USUARIO_ID_USUARIO")
	  REFERENCES "HT"."T_USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_PESOS
--------------------------------------------------------

  ALTER TABLE "HT"."T_PESOS" ADD CONSTRAINT "T_PESOS_T_USUARIO_FK" FOREIGN KEY ("T_USUARIO_ID_USUARIO")
	  REFERENCES "HT"."T_USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_PRESSAO
--------------------------------------------------------

  ALTER TABLE "HT"."T_PRESSAO" ADD CONSTRAINT "T_PRESSAO_T_USUARIO_FK" FOREIGN KEY ("T_USUARIO_ID_USUARIO")
	  REFERENCES "HT"."T_USUARIO" ("ID_USUARIO") ENABLE;
